
module.exports = {
	DisconnectReason: {
		BANNED: "Gebannt",
		IDLE_TIMEOUT: "Inaktivität",
		KICKED: "Durch Server-Administrator gekickt",
		MANUAL: "Spiel verlassen",
		PING_TIMEOUT: "Zeitüberschreitung"
	},
	ErrorCode: {
		ALREADY_STARTED: "alreadyStarted",
		ALREADY_STOPPED: "alreadyStopped",
		BAD_REQUEST: "badRequest",
		BANNED: "banned",
		CANNOT_JOIN_ANOTHER_GAME: "cannotJoinAnotherGame",
		GAME_FULL: "gameFull",
		INVALID_GAME: "invalidGame",
		INVALID_NICK: "invalidNick",
		NICK_IN_USE: "nickInUse",
		NO_GAME_SPECIFIED: "noGameSpecified",
		NO_MSG_SPECIFIED: "noMsgSpecified",
		NO_NICK_SPECIFIED: "noNickSpecified",
		NOT_ADMIN: "notAdmin",
		NOT_ENOUGH_PLAYERS: "notEnoughPlayers",
		NOT_GAME_HOST: "notGameHost",
		NOT_IN_THAT_GAME: "notInThatGame",
		SERVER_ERROR: "serverError",
		SOCKET_ID_IN_USE: "socketIdInUse",
		TOO_MANY_GAMES: "tooManyGames",
		TOO_MANY_USERS: "tooManyUsers",
		WRONG_PASSWORD: "wrongPassword"
	},
	ErrorMessage: {
		ALREADY_STARTED: "Das Spiel wurde bereits gestartet.",
		ALREADY_STOPPED: "Das Spiel wurde bereits beendet.",
		BAD_REQUEST: "Fehlerhafte Anfrage.",
		BANNED: "Gebannt.",
		CANNOT_JOIN_ANOTHER_GAME: "Du kannst keinem anderen Spiel beitreten.",
		GAME_FULL: "Das Spiel ist voll. Trete einem anderen Spiel bei.",
		INVALID_GAME: "Ungültiger Name angegeben.",
		NICK_IN_USE: "Benutzername wird bereits verwendet.",
		NO_GAME_SPECIFIED: "Kein Spiel angegeben.",
		NO_NICK_SPECIFIED: "Kein Benutzername angegeben.",
		NOT_ADMIN: "Du bist kein Administrator.",
		NOT_ENOUGH_PLAYERS: "Es sind nicht genug Spieler beigetreten, um das Spiel starten zu können.",
		NOT_GAME_HOST: "Nur der Spiel-Host darf das tun.",
		NOT_IN_THAT_GAME: "Du bist nicht in diesem Spiel.",
		SERVER_ERROR: "Auf dem Server ist ein Fehler aufgetreten.",
		SOCKET_ID_IN_USE: "Deine Socket-ID wird bereits verwendet. Kontaktiere einen Administrator, um den Server neuzustarten!",
		TOO_MANY_GAMES: "Derzeit laufen zu viele Spiele. Trete entweder einem existierenden bei, oder warte, bis wieder eins verfügbar ist.",
		TOO_MANY_USERS: "Es sind zu viele Benutzer verbunden. Warte darauf, dass ein Benutzer den Server verlässt.",
		WRONG_PASSWORD: "Das Passwort ist falsch."
	},
	EventDetail: {
		ERROR: "error",
		ERROR_CODE: "errorCode",
		EVENT: "event",
		FROM: "from",
		FROM_ADMIN: "fromAdmin",
		GAME_BUNDLE: "gameBundle",
		GAME_ID: "gameId",
		GAME_INFO: "gameInfo",
		GAME_LIST: "gameList",
		GAME_OPTIONS: "gameOptions",
		GAME_PASSWORD: "gamePassword",
		GAME_STATE: "gameState",
		SOCKET_ID: "socketId",
		INTERMISSION: "intermission",
		MESSAGE: "message",
		NICKNAME: "nickname",
		PLAYER_INFO: "playerInfo",
		REASON: "reason",
		ROUND_WINNER: "roundWinner",
		SPECTATOR_INFO: "spectatorInfo",
		TIMESTAMP: "timestamp"
	},
	EventType: {
		BANNED: "banned",
		CHAT: "chat",
		GAME_CREATE: "gameCreate",
		GAME_JOIN: "gameJoin",
		GAME_LEAVE: "gameLeave",
		GAME_LIST_REFRESH: "gameListRefresh",
		GAME_OPTIONS_CHANGED: "gameOptionsChanged",
		GAME_PLAYER_INFO_CHANGE: "gamePlayerInfoChange",
		GAME_PLAYER_JOIN: "gamePlayerJoin",
		GAME_PLAYER_KICKED_IDLE: "gamePlayerKickedIdle",
		GAME_PLAYER_LEAVE: "gamePlayerLeave",
		GAME_PLAYER_SKIPPED: "gamePlayerSkipped",
		GAME_SPECTATOR_JOIN: "gameSpectatorJoin",
		GAME_SPECTATOR_LEAVE: "gameSpectatorLeave",
		GAME_ROUND_COMPLETE: "gameRoundComplete",
		GAME_START: "gameStart",
		GAME_STATE_CHANGE: "gameStateChange",
		KICKED: "kicked",
		KICKED_FROM_GAME_IDLE: "kickedFromGameIdle",
		NEW_PLAYER: "newPlayer",
		PLAYER_LEAVE: "playerLeave"
	},
	GameBundleInfo: {
		AUTHOR: "author",
		CLIENT_DIRECTORY: "clientDir",
		DISPLAY_NAME: "displayName",
		NAME: "name",
		ROUTE: "route",
		VERSION: "version",
	},
	GameInfo: {
		CREATED: "created",
		GAME_BUNDLE: "gameBundle",
		GAME_OPTIONS: "gameOptions",
		HAS_PASSWORD: "hasPassword",
		HOST: "host",
		ID: "id",
		PLAYERS: "players",
		SPECTATORS: "spectators"
	},
	GamePlayerInfo: {
		NAME: "name",
		SOCKET_ID: "socketId"
	},
	GameOptionData: {
		PASSWORD: "password",
		PLAYER_LIMIT: "playerLimit",
		SPECTATOR_LIMIT: "spectatorLimit"
	},
	MessageType: {
		CHAT: "chat",
		CLIENT_EVENT: "clientEvent",
		ERROR: "error",
		GAME_EVENT: "gameEvent",
		GAME_PLAYER_EVENT: "gamePlayerEvent",
		PLAYER_EVENT: "playerEvent"
	}
}